   name: CI

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'

       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           python -m pip install setuptools
           python -m pip install wheel
           python -m pip install -e .

       - name: Run tests
         run: |
           python -m unittest discover -s tests -p 'test_core.py'

       - name: Build package
         run: |
           python setup.py sdist bdist_wheel

       - name: Publish package to PyPI
         env:
           TWINE_USERNAME: __token__
           TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
         run: |
           pip install twine
           twine upload dist/*